
version: '3.8'

services:
  redis:
    image: redis:7.2.3-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

  redis-test:
    image: redis:7.2.3-alpine
    restart: always
    ports:
      - '1234:6379'
    command: redis-server

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
volumes:
  cache:
    driver: local
